<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="106708" started-at="2020-12-10T14:46:09 IST" finished-at="2020-12-10T14:47:55 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="106708" started-at="2020-12-10T14:46:09 IST" finished-at="2020-12-10T14:47:55 IST">
      <class name="com.ds.automation.executionengine.testrunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.ds.automation.executionengine.testrunner@2353b3e6]" name="setUpClass" is-config="true" duration-ms="19976" started-at="2020-12-10T14:46:09 IST" finished-at="2020-12-10T14:46:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.ds.automation.executionengine.testrunner@2353b3e6]" name="feature" duration-ms="80868" started-at="2020-12-10T14:46:30 IST" data-provider="features" finished-at="2020-12-10T14:47:51 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA["Case creation and case creation validation"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Create Case"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to click on New button]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to click on New button
at org.testng.Assert.fail(Assert.java:97)
at com.ds.automation.steps.CaseToKnowledge_Steps.clickOnCasesNew1Button(CaseToKnowledge_Steps.java:67)
at âœ½.Click on Cases New button to create case(./features/CaseCreation.feature:6)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass(org.testng.ITestContext)[pri:0, instance:com.ds.automation.executionengine.testrunner@2353b3e6]" name="tearDownClass" is-config="true" duration-ms="3840" started-at="2020-12-10T14:47:51 IST" finished-at="2020-12-10T14:47:55 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@323659f8]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.ds.automation.executionengine.testrunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
